"""new0_migration

Revision ID: 38819438709a
Revises: c87812bed44c
Create Date: 2024-04-30 10:48:30.778374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38819438709a'
down_revision = 'c87812bed44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('uploadfile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploadfile', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
