"""new1_migration

Revision ID: 598e0cda1915
Revises: 6040182e8327
Create Date: 2024-04-29 11:33:29.147500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598e0cda1915'
down_revision = '6040182e8327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(), nullable=True))
        batch_op.drop_index('ix_users_quiztitle')
        batch_op.drop_column('quiztitle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiztitle', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_users_quiztitle', ['quiztitle'], unique=False)
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
