"""new2_migration

Revision ID: 8e4c38f491b1
Revises: 598e0cda1915
Create Date: 2024-04-29 12:54:50.836410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4c38f491b1'
down_revision = '598e0cda1915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('textword', sa.String(), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('textword')

    # ### end Alembic commands ###
